### ISSUE TITLE
PYNZ-Z1 image version ？

### ISSUE THREAD

**Issue by cverzq** [ms0488638/PYNQ_Burst_Test#1]
Excuse me, can you tell me that you use which version  PYNQ image version is?  v2.0, v2.1, v2.3?  thank you very much

**Comment by cverzq** [comment]
@ms0488638

**Comment by ms0488638** [comment]
I think it's v2.4. But the newer version is fine.

My board is now updated to v2.5, but it still works as flow.

**Comment by cverzq** [comment]
> I think it's v2.4. But the newer version is fine.
> 
> My board is now updated to v2.5, but it still works as flow.

thank for your answer. I try to do it
